### ISSUE TITLE
Colorpicker hex(#) 분리시키기

### ISSUE THREAD

**Issue by TaeWoongKim2** [Team-Rocket-TR/BannerMaker#39]
### Colorpicker hex(#) 분리시키기

반응형을 구현하기 어려움에 따라 'react-color'에 대한 Hex Input을 따로 만들 필요가 있을 것 같습니다.

UI/UX 적으로 더 편할 것 같습니다!

<br />

※ Hex to RGB 혹은 RGB to Hex 에 대한 계산법은 아래의 참조링크를 확인해주세요.
- https://stackoverflow.com/questions/5623838/rgb-to-hex-and-hex-to-rgb

**Comment by raeyoung** [comment]
참고링크
https://css-tricks.com/converting-color-spaces-in-javascript/

**Comment by raeyoung** [comment]
hex input 값 변경 시 error 발생

**Comment by raeyoung** [comment]
1. RGBtoHex & HextoRGB 성공
2. Hex 자리수가 달라질 경우 에러 발생.
